# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "nixos-cluster-terraform-states"
    endpoint                    = "http://chungus.private:9000/"
    force_path_style            = true
    key                         = "dev/network/terraform.tfstate"
    region                      = "home"
    skip_credentials_validation = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
  }
}
