# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
includes = [ "*.nix"]

[formatter.shell]
command = "shfmt"
options = [
    "-i",
    "2",  # indent 2
    "-s",  # simplify the code
    "-w",  # write back to the file
]
includes = ["*.sh"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.python]
command = "black"
includes = ["*.py"]

[formatter.media]
command = "prettier"
options = ["--write"]
includes = [
    "*.json",
    "*.md",
    "*.yaml",
    "*.yml",
]
excludes = [
    "./machines/*.json"
]

[formatter.terragrunt]
command = "terragrunt"
options = [ "hclfmt" ]
includes = [ "*.hcl" ]
excludes = [ "*/.terraform" ]

[formatter.terraform]
command = "terraform"
options = [ "fmt" ]
includes = [ "*.tf" ]
excludes = [ "*/.terraform" ]

[formatter.nomad]
command = "nomad"
options = [ "fmt" ]
includes = [ "*.nomad" ]
