# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# terragrunt functions
locals {
  path_relative_to_include   = "dev/core-servers"
  path_relative_from_include = "../.."
  get_repo_root              = "/home/palo/dev/nixos/nixos-cluster"
  get_path_to_repo_root      = "../../../../"
  get_path_from_repo_root    = "terraform/targets/dev/core-servers"
}

variable "environment" {}
